name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'datapackage.json'
      - 'docs/**.md'
      - 'docs/**.html'
      - 'docs/**.css'
      - 'generate_docs_pipeline.py'
      - 'custom.css'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install livemark markdown

      - name: Generate Documentation
        run: python generate_docs_pipeline.py

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
