name: Build and Deploy Documentation

on:
  push:
    paths:
      - 'datapackage.json'
      - 'docs/**.md'
      - 'generate_docs_pipeline.py'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Required for pushing to gh-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install livemark markdown
          pip install markdown

      - name: Run docs generation script
        run: python generate_docs_pipeline.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs  # ✅ Match the OUTPUT_DIR in your script
